[package]
name = "mosaic"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ljp-projects/mosaic"

[profile.dev]
incremental = true
panic = "unwind"

[profile.test]

[profile.bench]
lto = "fat"
overflow-checks = false
opt-level = 3
incremental = true
debug-assertions = false
debug = "line-tables-only"

[profile.release]
lto = "fat"
overflow-checks = false
opt-level = 3
incremental = true
debug-assertions = false
debug = "line-tables-only"
panic = "unwind"

[dependencies]
cranelift-codegen = { version = "0.114.0", features = ["all-arch"] }
cranelift-module = "0.114.0"
cranelift-object = "0.114.0"
cranelift-native = "0.114.0"
cranelift-frontend = "0.114.0"
target-lexicon = "0.12.16"
colored = "2.2.0"