[package]
name = "mosaic"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Plumb"]
keywords = ["compiler", "Mosaic"]
readme = "README.md"
rust-version = "1.80.0"
license-file = "LICENSE"
description = "A compiler for Mosaic."
categories = ["compilers"]
publish = true
repository = "https://github.com/ljp-projects/mosaic"

[profile.dev]
incremental = true
panic = "unwind"

[profile.bench]
lto = "fat"
overflow-checks = false
opt-level = 3
incremental = true
debug-assertions = false
debug = "line-tables-only"

[profile.release]
lto = "fat"
overflow-checks = false
opt-level = 3
incremental = true
debug-assertions = false
debug = "line-tables-only"
panic = "abort"

[dependencies]
cranelift-codegen = { version = "0.115.0", features = ["all-arch"] }
cranelift-module = "0.115.0"
cranelift-object = "0.115.0"
cranelift-native = "0.115.0"
cranelift-frontend = "0.115.0"
colored = "2.2.0"
either = "1.13.0"

# cranelift uses target-lexicon 0.12.16
target-lexicon = "0.12.16"