[package]
name = "mosaic"
version = "0.1.0"
edition = "2021"

[profile.bench]
lto = "fat"
overflow-checks = false
opt-level = 3
incremental = true
debug-assertions = false
debug = "line-tables-only"

[profile.release]
lto = "fat"
overflow-checks = false
opt-level = 3
incremental = true
debug-assertions = false
debug = "line-tables-only"

[dependencies]
filename = "0.1.1"
serde = { version = "1.0.214", features = ["derive"] }